---
title: "Practice"
description: Experimental Design and Data Analysis for the Cognitive and Brain Sciences
output:
  html_document:
    toc: false
    theme: cosmo
fontsize: 14pt
---

## Old tutorial resources

- `R` basics
  - <a href="tutorials/tutorial_1.html" target="_blank">Tutorial 1 worksheet</a>

- `data.table`
  - <a href="tutorials/tutorial_2.html" target="_blank">Tutorial 2 worksheet</a>

- `ggplot`
  - <a href="tutorials/tutorial_3.html" target="_blank">Tutorial 3 worksheet</a>

- Data wrangling and descriptive statistics
  - <a href="tutorials/tutorial_4.html" target="_blank">Tutorial 4 worksheet</a>

- Random variables and probability distributions
  - <a href="tutorials/tutorial_5.html" target="_blank">Tutorial 5 worksheet</a>

- Null hypothesis significance testing
  - <a href="tutorials/tutorial_6.html" target="_blank">Tutorial 6 worksheet</a>

- Null hypothesis significance testing 2
  - <a href="tutorials/tutorial_7.html" target="_blank">Tutorial 7 worksheet</a>


## Old problem sets

- 2024 problem set 1
  - <a href="homework/homework_1.html" target="_blank">Problem set 1 worksheet</a>

- 2024 problem set 1 solutions
  - <a href="homework/homework_1_solutions.html" target="_blank">Problem set 1 worksheet solutions</a>

- 2024 problem set 2
  - <a href="homework/homework_2.html" target="_blank">Problem set 2 worksheet</a>

- 2024 problem set 2 solutions
  - <a href="homework/homework_2_solutions.html" target="_blank">Problem set 2 worksheet solutions</a>

- 2024 problem set 3
  - <a href="homework/homework_3.html" target="_blank">Problem set 3 worksheet</a>

- 2024 problem set 3 solutions
  - <a href="homework/homework_3_pdf_solutions.pdf" target="_blank">Problem set 3 worksheet solutions</a>

- 2024 problem set 4
  - <a href="homework/homework_4.html" target="_blank">Problem set 4 worksheet</a>

- 2024 problem set 4 solutions
  - <a href="homework/homework_4_pdf_solutions.pdf" target="_blank">Problem set 4 worksheet solutions</a>


## Old final exam practice

- 2024 final exam practice
  - <a href="homework/final_exam_study_material.pdf" target="_blank">Final exam practice worksheet</a>
